package top.palexu.blockchaincredit.report.dao;

import top.palexu.blockchaincredit.report.model.FactorScriptRelation;

public interface FactorScriptRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factor_script_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factor_script_relation
     *
     * @mbg.generated
     */
    int insert(FactorScriptRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factor_script_relation
     *
     * @mbg.generated
     */
    int insertSelective(FactorScriptRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factor_script_relation
     *
     * @mbg.generated
     */
    FactorScriptRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factor_script_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FactorScriptRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factor_script_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FactorScriptRelation record);
}