package top.palexu.blockchaincredit.report.dao;

import org.apache.ibatis.annotations.Param;
import top.palexu.blockchaincredit.report.model.FactorTemplateRelation;

import java.util.List;

public interface FactorTemplateRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factor_Template_relation
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factor_Template_relation
     */
    int insert(FactorTemplateRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factor_Template_relation
     */
    int insertSelective(FactorTemplateRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factor_Template_relation
     */
    FactorTemplateRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factor_Template_relation
     */
    int updateByPrimaryKeySelective(FactorTemplateRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factor_Template_relation
     */
    int updateByPrimaryKey(FactorTemplateRelation record);

    List<Long> findFactorIdByTemplateId(Long id);

    int deleteByFactorIdAndTemplateId(@Param("templateId") Long templateId, @Param("factorId") Long factorId);
}