package top.palexu.blockchaincredit.report.dao;

import top.palexu.blockchaincredit.report.model.FactorTemplateRelation;

import java.util.List;

public interface FactorTemplateRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factor_Template_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factor_Template_relation
     *
     * @mbg.generated
     */
    int insert(FactorTemplateRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factor_Template_relation
     *
     * @mbg.generated
     */
    int insertSelective(FactorTemplateRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factor_Template_relation
     *
     * @mbg.generated
     */
    FactorTemplateRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factor_Template_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FactorTemplateRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factor_Template_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FactorTemplateRelation record);

    List<Long> findFactorIdByTemplateId(Long id);
}