package top.palexu.blockchaincredit.report.dao;

import top.palexu.blockchaincredit.report.model.FactorDo;

import java.util.List;

public interface FactorDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factor
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factor
     *
     * @mbg.generated
     */
    int insert(FactorDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factor
     *
     * @mbg.generated
     */
    int insertSelective(FactorDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factor
     *
     * @mbg.generated
     */
    FactorDo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factor
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FactorDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factor
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FactorDo record);

    List<FactorDo> selectByScriptId(Long id);
}