package top.palexu.blockchaincredit.report.dao;

import top.palexu.blockchaincredit.report.model.Factor;

public interface FactorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factor
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factor
     *
     * @mbg.generated
     */
    int insert(Factor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factor
     *
     * @mbg.generated
     */
    int insertSelective(Factor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factor
     *
     * @mbg.generated
     */
    Factor selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factor
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Factor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factor
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Factor record);
}