package top.palexu.blockchaincredit.report.dao;

import top.palexu.blockchaincredit.report.model.Script;

public interface ScriptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table script
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table script
     *
     * @mbg.generated
     */
    int insert(Script record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table script
     *
     * @mbg.generated
     */
    int insertSelective(Script record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table script
     *
     * @mbg.generated
     */
    Script selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table script
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Script record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table script
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Script record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table script
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Script record);
}